### PR TITLE
Feature/checkstyle

### PR DESCRIPTION
**Pull request by christianhoff**
**Motivation**
All source code files must follow the AOSP format and style.

**Changes**
* use Spotless Gradle plugin to format code using google-java-format in AOSP format
* provide IntelliJ IDEA configuration to match AOSP format
* use checkstyle to enforce coding style

### CODE REVIEW

**Comment by SgtSilvio** [comment]
Does the IntelliJ formatter with the AOSP config imported generate the same output as the Spotless Gradle plugin?

**Comment by clive-jevons** [comment]
I did a quick test - checked out the branch, configured IntelliJ as documented, created a new class, formatted with IntelliJ, then gradle build. First attempt failed due to missing license, so used gradle licenseFormat to add it, then built, and spotless failed because the license was poorly formatted (it said), so formatted that in intellij and built, but now the license check failed because the license was reformatted. Seems to be a catch 22. What am I doing wrong?

**Comment by christianhoff** [comment]
Yes, the output of Spotless and IntelliJ should be the same. Please follow the instructions in README.md to configure your IDE appropriately.

**Comment by SgtSilvio** [comment]
Closed as outdated

**Pull request closed without merging**
