### PR TITLE
Added custom http headers to MqttWebSocket

### PR DESCRIPTION
**Pull request by hctemmel**
**Motivation**
Added the option to add custom http headers (eg bearer token authentication to reverse proxy) for websocket connection

**Changes**
MqttWebSocketConfig

### CODE REVIEW

**Comment by SgtSilvio** [comment]
@hctemmel Thank you for your contribution.
It seems to be pretty good, but before we can review and incorporate it, you need to sign our CLA.
Please follow the instruction of the cla-bot's comment. If something is unclear please just ask.

**Comment by skrutzler** [comment]
It took a while but the CLA is now signed and was sent to contributing@hivemq.com

**Comment by skrutzler** [comment]
Hello @SgtSilvio. Do you need anything else from my side to start the review process?
Thanks a lot and best regards.

**Comment by SgtSilvio** [comment]
@cla-bot check

**Comment by SgtSilvio** [comment]
Sorry, please ignore the above messages from the cla-bot, I need to check who has access to contributing@hivemq.com

**Comment by MagiErber** [comment]
@cla-bot check

**Comment by MagiErber** [comment]
Hi @skrutzler, thank you for your contribution! Unfortunately the GitHub username (skrutzler) is not part of the list. Can you please send us an updated signed CLA with this username on the list as well? Thank you!

**Comment by skrutzler** [comment]
> Hi @skrutzler, thank you for your contribution! Unfortunately the GitHub username (skrutzler) is not part of the list. Can you please send us an updated signed CLA with this username on the list as well? Thank you!

Hello. My username (preto) was on the signed CLA. skrutzler is just the changed nickname and belongs to the same registered user ( click on my profile to see it ;) @skrutzler )

**Comment by skrutzler** [comment]
@cla-bot check

**Comment by skrutzler** [comment]
@SgtSilvio I think all requirements are met now and it can be merged if there are not any remarks.

Do you know by any chance when a new release with those changes might be triggered?

**Comment by skrutzler** [comment]
is there anything still missing on our end @SgtSilvio ?

**Comment by pglombardo** [comment]
Hi @skrutzler - thanks for staying on top of this and traversing the cla bot.  Either I or @SgtSilvio will take a look at this very soon and post an update.

**Comment by pglombardo** [comment]
Thanks for your work and patience on this @skrutzler!  PR is merged.  We'll put out a new release soon.

**Pull request merged**
