### PR TITLE
Improvement/add-methods-consuming-collection

### LINKED ISSUE #170: Add methods consuming Collection for Subscribe/UnsubscribeBuilder

### PR DESCRIPTION
**Pull request by MicWalter**
**Motivation**
It should be easy to add a dynamic amount of topics to a Subscribe/Unsubscribe packet or User Properties to any packet.

Resolves #170

**Changes**
Added methods that consume collection for:
- Mqtt3/Mqtt5 Subscribe Builder
- Mqtt3/Mqtt5 Unsubscribe Builder
- UserProperties Builder

### CODE REVIEW

**Comment by MicWalter** [comment]
Related to https://github.com/hivemq/hivemq-mqtt-client/issues/170

**Comment by SgtSilvio** [comment]
Nice PR 👍 
Some general feedback:
- We should take `Collection` as argument instead of `List` so passing a `Set` is also possible
- We should additionally provide methods with an array (varargs) as an argument
- We should additionally provide methods with a `Stream` as an argument. This allows the user to e.g. specify a list of topic filters with the same QoS:
```java
List<String> topicFilters = Arrays.asList("test", "hello", "world");
MqttQos qos = MqttQos.EXACTLY_ONCE;
Mqtt5Subscribe.builder()
        .addSubscriptions(topicFilters.stream().map(topicFilter -> 
                Mqtt5Subscription.builder().topicFilter(topicFilter).qos(qos).build()))
        .build();
```
This would also allow us to only take `Collection<MqttTopicFilter>` and not `Collection<String>` as argument to `addTopicFilters`:
```java
List<String> topicFilters = Arrays.asList("test", "hello", "world");
Mqtt5Unsubscribe.builder().addTopicFilters(topicFilters.stream().map(MqttTopicFilter::of)).build();
```

**Comment by SgtSilvio** [comment]
Resolves #170

**Comment by SgtSilvio** [comment]
I removed the label and milestone as we have a ticket for tracking this data: #170
PRs are only labelled and included in projects and milestones if no corresponding issue exists, so the PR acts as both ticket and PR.

**Pull request merged**
